class CreateDjwages < ActiveRecord::Migration[5.1]
  def change
    create_table :djwages do |t|
      t.integer :employee_id
      t.integer :month
      t.integer :year
      t.string :col1
      t.string :col2
      t.float :col3
      t.float :col4
      t.float :col5
      t.float :col6
      t.float :col7
      t.float :col8
      t.float :col9
      t.float :col10
      t.float :col11
      t.float :col12
      t.float :col13
      t.float :col14
      t.float :col15
      t.float :col16
      t.float :col17
      t.float :col18
      t.float :col19
      t.float :col20
      t.float :col21
      t.float :col22
      t.float :col23
      t.float :col24
      t.float :col25
      t.float :col26
      t.float :col27
      t.float :col28
      t.float :col29
      t.float :col30
      t.float :col31
      t.float :col32
      t.float :col33
      t.float :col34
      t.float :col35
      t.float :col36
      t.float :col37
      t.float :col38
      t.float :col39
      t.float :col40
      t.float :col41
      t.float :col42
      t.float :col43
      t.float :col44
      t.float :col45
      t.float :col46
      t.float :col47
      t.float :col48
      t.float :col49
      t.float :col50
      t.float :col51
      t.float :col52
      t.float :col53
      t.float :col54
      t.float :col55
      t.float :col56
      t.float :col57
      t.float :col58
      t.float :col59
      t.float :col60
      t.float :col61
      t.float :col62
      t.float :col63
      t.float :col64
      t.float :col65
      t.float :col66
      t.float :col67
      t.float :col68
      t.float :col69
      t.float :col70
      t.float :col71
      t.float :col72
      t.float :col73
      t.float :col74
      t.float :col75
      t.float :col76
      t.float :col77
      t.float :col78
      t.float :col79
      t.float :col80
      t.float :col81
      t.float :col82
      t.float :col83
      t.float :col84
      t.float :col85
      t.float :col86
      t.float :col87
      t.float :col88
      t.float :col89
      t.float :col90
      t.float :col91
      t.float :col92
      t.float :col93
      t.float :col94
      t.float :col95
      t.float :col96
      t.float :col97
      t.float :col98
      t.float :col99
      t.timestamps
    end
  end
end
