class ChangeDataTypeOfWageAndBonus < ActiveRecord::Migration[5.1]
  def change
    change_column :wages,:col13,:float
    change_column :wages,:col14,:float
    change_column :wages,:col15,:float
    change_column :wages,:col16,:float
    change_column :wages,:col17,:float
    change_column :wages,:col18,:float
    change_column :wages,:col19,:float
    change_column :wages,:col20,:float
    change_column :wages,:col21,:float
    change_column :wages,:col22,:float
    change_column :wages,:col23,:float
    change_column :wages,:col24,:float
    change_column :wages,:col25,:float
    change_column :wages,:col26,:float
    change_column :wages,:col27,:float
    change_column :wages,:col28,:float
    change_column :wages,:col29,:float
    change_column :wages,:col30,:float
    change_column :wages,:col31,:float
    change_column :wages,:col32,:float
    change_column :wages,:col33,:float
    change_column :wages,:col34,:float
    change_column :wages,:col35,:float
    change_column :wages,:col36,:float
    change_column :wages,:col37,:float
    change_column :wages,:col38,:float
    change_column :wages,:col39,:float
    change_column :wages,:col40,:float
    change_column :wages,:col41,:float
    change_column :wages,:col42,:float
    change_column :wages,:col43,:float
    change_column :wages,:col44,:float
    change_column :wages,:col45,:float
    change_column :wages,:col46,:float
    change_column :wages,:col47,:float
    change_column :wages,:col48,:float
    change_column :wages,:col49,:float
    change_column :wages,:col50,:float
    change_column :wages,:col51,:float
    change_column :wages,:col52,:float
    change_column :wages,:col53,:float
    change_column :wages,:col54,:float
    change_column :wages,:col55,:float
    change_column :wages,:col56,:float
    change_column :wages,:col57,:float
    change_column :wages,:col58,:float
    change_column :wages,:col59,:float
    change_column :wages,:col60,:float
    change_column :wages,:col61,:float
    change_column :wages,:col62,:float
    change_column :wages,:col63,:float
    change_column :wages,:col64,:float
    change_column :wages,:col65,:float
    change_column :wages,:col66,:float
    change_column :wages,:col67,:float
    change_column :wages,:col68,:float
    change_column :wages,:col69,:float
    change_column :wages,:col70,:float
    change_column :wages,:col71,:float
    change_column :wages,:col72,:float
    change_column :wages,:col73,:float
    change_column :wages,:col74,:float
    change_column :wages,:col75,:float
    change_column :wages,:col76,:float
    change_column :wages,:col77,:float
    change_column :wages,:col78,:float
    change_column :wages,:col79,:float
    change_column :wages,:col80,:float
    change_column :wages,:col81,:float
    change_column :wages,:col82,:float
    change_column :wages,:col83,:float
    change_column :wages,:col84,:float
    change_column :wages,:col85,:float
    change_column :wages,:col86,:float
    change_column :wages,:col87,:float
    change_column :wages,:col88,:float
    change_column :wages,:col89,:float
    change_column :wages,:col90,:float
    change_column :wages,:col91,:float
    change_column :wages,:col92,:float
    change_column :wages,:col93,:float
    change_column :wages,:col94,:float
    change_column :wages,:col95,:float
    change_column :wages,:col96,:float
    change_column :wages,:col97,:float
    change_column :wages,:col98,:float
    change_column :wages,:col99,:float

    change_column :bonus,:col8,:float
    change_column :bonus,:col9,:float
    change_column :bonus,:col10,:float
    change_column :bonus,:col11,:float
    change_column :bonus,:col12,:float
    change_column :bonus,:col13,:float
    change_column :bonus,:col14,:float
    change_column :bonus,:col15,:float
    change_column :bonus,:col16,:float
    change_column :bonus,:col17,:float
    change_column :bonus,:col18,:float
    change_column :bonus,:col19,:float
    change_column :bonus,:col20,:float
    change_column :bonus,:col21,:float
    change_column :bonus,:col22,:float
    change_column :bonus,:col23,:float
    change_column :bonus,:col24,:float
    change_column :bonus,:col25,:float
    change_column :bonus,:col26,:float
    change_column :bonus,:col27,:float
    change_column :bonus,:col28,:float
    change_column :bonus,:col29,:float
    change_column :bonus,:col30,:float
    change_column :bonus,:col31,:float
    change_column :bonus,:col32,:float
    change_column :bonus,:col33,:float
    change_column :bonus,:col34,:float
    change_column :bonus,:col35,:float
    change_column :bonus,:col36,:float
    change_column :bonus,:col37,:float
    change_column :bonus,:col38,:float
    change_column :bonus,:col39,:float
    change_column :bonus,:col40,:float
    change_column :bonus,:col41,:float
    change_column :bonus,:col42,:float
    change_column :bonus,:col43,:float
    change_column :bonus,:col44,:float
    change_column :bonus,:col45,:float
    change_column :bonus,:col46,:float
    change_column :bonus,:col47,:float
    change_column :bonus,:col48,:float
    change_column :bonus,:col49,:float
    change_column :bonus,:col50,:float
    change_column :bonus,:col51,:float
    change_column :bonus,:col52,:float
    change_column :bonus,:col53,:float
    change_column :bonus,:col54,:float
    change_column :bonus,:col55,:float
    change_column :bonus,:col56,:float
    change_column :bonus,:col57,:float
    change_column :bonus,:col58,:float
    change_column :bonus,:col59,:float
    change_column :bonus,:col60,:float
    change_column :bonus,:col61,:float
    change_column :bonus,:col62,:float
    change_column :bonus,:col63,:float
    change_column :bonus,:col64,:float
    change_column :bonus,:col65,:float
    change_column :bonus,:col66,:float
    change_column :bonus,:col67,:float
    change_column :bonus,:col68,:float
    change_column :bonus,:col69,:float
    change_column :bonus,:col70,:float
    change_column :bonus,:col71,:float
    change_column :bonus,:col72,:float
    change_column :bonus,:col73,:float
    change_column :bonus,:col74,:float
    change_column :bonus,:col75,:float
    change_column :bonus,:col76,:float
    change_column :bonus,:col77,:float
    change_column :bonus,:col78,:float
    change_column :bonus,:col79,:float
    change_column :bonus,:col80,:float
  end
end
