class CreateKuaizhaoContents < ActiveRecord::Migration[5.1]
  def change
    create_table :kuaizhao_contents do |t|
      t.json :formula
      t.string :name
      t.integer :year
      t.integer :month
      t.string  :category
      t.integer :col1
      t.integer :col2
      t.integer :col3
      t.integer :col4
      t.integer :col5
      t.integer :col6
      t.integer :col7
      t.integer :col8
      t.integer :col9
      t.integer :col10
      t.integer :col11
      t.integer :col12
      t.integer :col13
      t.integer :col14
      t.integer :col15
      t.integer :col16
      t.integer :col17
      t.integer :col18
      t.integer :col19
      t.integer :col20
      t.integer :col21
      t.integer :col22
      t.integer :col23
      t.integer :col24
      t.integer :col25
      t.integer :col26
      t.integer :col27
      t.integer :col28
      t.integer :col29
      t.integer :col30
      t.integer :col31
      t.integer :col32
      t.integer :col33
      t.integer :col34
      t.integer :col35
      t.integer :col36
      t.integer :col37
      t.integer :col38
      t.integer :col39
      t.integer :col40
      t.integer :col41
      t.integer :col42
      t.integer :col43
      t.integer :col44
      t.integer :col45
      t.integer :col46
      t.integer :col47
      t.integer :col48
      t.integer :col49
      t.integer :col50
      t.integer :col51
      t.integer :col52
      t.integer :col53
      t.integer :col54
      t.integer :col55
      t.integer :col56
      t.integer :col57
      t.integer :col58
      t.integer :col59
      t.integer :col60
      t.integer :col61
      t.integer :col62
      t.integer :col63
      t.integer :col64
      t.integer :col65
      t.integer :col66
      t.integer :col67
      t.integer :col68
      t.integer :col69
      t.integer :col70
      t.integer :col71
      t.integer :col72
      t.integer :col73
      t.integer :col74
      t.integer :col75
      t.integer :col76
      t.integer :col77
      t.integer :col78
      t.integer :col79
      t.integer :col80
      t.timestamps
    end
  end
end
