class ChangeColumnOtherAwardsTotals < ActiveRecord::Migration[5.1]
  def change
    rename_column :other_award_totals,:奖励1,:col1
    rename_column :other_award_totals,:奖励2,:col2
    rename_column :other_award_totals,:奖励3,:col3
    rename_column :other_award_totals,:奖励4,:col4
    rename_column :other_award_totals,:奖励5,:col5
    rename_column :other_award_totals,:奖励6,:col6
    add_column :other_award_totals,:col7,:string
    add_column :other_award_totals,:col8,:string
    add_column :other_award_totals,:col9,:string
    add_column :other_award_totals,:col10,:string
    add_column :other_award_totals,:col11,:string
    add_column :other_award_totals,:col12,:string
    add_column :other_award_totals,:col13,:string
    add_column :other_award_totals,:col14,:string
    add_column :other_award_totals,:col15,:string
    add_column :other_award_totals,:col16,:string
    add_column :other_award_totals,:col17,:string
    add_column :other_award_totals,:col18,:string
    add_column :other_award_totals,:col19,:string
    add_column :other_award_totals,:col20,:string
    add_column :other_award_totals,:col21,:string
    add_column :other_award_totals,:col22,:string
    add_column :other_award_totals,:col23,:string
    add_column :other_award_totals,:col24,:string
    add_column :other_award_totals,:col25,:string
    add_column :other_award_totals,:col26,:string
    add_column :other_award_totals,:col27,:string
    add_column :other_award_totals,:col28,:string
    add_column :other_award_totals,:col29,:string
    add_column :other_award_totals,:col30,:string
    add_column :other_award_totals,:col31,:string
    add_column :other_award_totals,:col32,:string
    add_column :other_award_totals,:col33,:string
    add_column :other_award_totals,:col34,:string
    add_column :other_award_totals,:col35,:string
    add_column :other_award_totals,:col36,:string
    add_column :other_award_totals,:col37,:string
    add_column :other_award_totals,:col38,:string
    add_column :other_award_totals,:col39,:string
    add_column :other_award_totals,:col40,:string
    add_column :other_award_totals,:col41,:string
    add_column :other_award_totals,:col42,:string
    add_column :other_award_totals,:col43,:string
    add_column :other_award_totals,:col44,:string
    add_column :other_award_totals,:col45,:string
    add_column :other_award_totals,:col46,:string
    add_column :other_award_totals,:col47,:string
    add_column :other_award_totals,:col48,:string
    add_column :other_award_totals,:col49,:string
    add_column :other_award_totals,:col50,:string
  end
end
