class AddColumnToWages < ActiveRecord::Migration[5.1]
  def change
    add_column :wages,:col100,:float
    add_column :wages,:col101,:float
    add_column :wages,:col102,:float
    add_column :wages,:col103,:float
    add_column :wages,:col104,:float
    add_column :wages,:col105,:float
    add_column :wages,:col106,:float
    add_column :wages,:col107,:float
    add_column :wages,:col108,:float
    add_column :wages,:col109,:float
    add_column :wages,:col110,:float
    add_column :wages,:col111,:float
    add_column :wages,:col112,:float
    add_column :wages,:col113,:float
    add_column :wages,:col114,:float
    add_column :wages,:col115,:float
    add_column :wages,:col116,:float
    add_column :wages,:col117,:float
    add_column :wages,:col118,:float
    add_column :wages,:col119,:float
    add_column :wages,:col120,:float
    add_column :wages,:col121,:float
    add_column :wages,:col122,:float
    add_column :wages,:col123,:float
    add_column :wages,:col124,:float
    add_column :wages,:col125,:float
    add_column :wages,:col126,:float
    add_column :wages,:col127,:float
    add_column :wages,:col128,:float
    add_column :wages,:col129,:float
    add_column :wages,:col130,:float
    add_column :wages,:col131,:float
    add_column :wages,:col132,:float
    add_column :wages,:col133,:float
    add_column :wages,:col134,:float
    add_column :wages,:col135,:float
    add_column :wages,:col136,:float
    add_column :wages,:col137,:float
    add_column :wages,:col138,:float
    add_column :wages,:col139,:float
    add_column :wages,:col140,:float
    add_column :wages,:col141,:float
    add_column :wages,:col142,:float
    add_column :wages,:col143,:float
    add_column :wages,:col144,:float
    add_column :wages,:col145,:float
    add_column :wages,:col146,:float
    add_column :wages,:col147,:float
    add_column :wages,:col148,:float
    add_column :wages,:col149,:float
    add_column :wages,:col150,:float
  end
end
